on:
  push:
    branches:
      - main
    paths:
      - lab4/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd lab4
          docker build -t atasik/jupyterhub .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run tests
        run: |
          echo "tested"

      - name: Push Docker image
        run: |
          docker push atasik/jupyterhub